### ISSUE TITLE
Weirdly long file

### ISSUE THREAD

**Issue by tymoczko** [DCMLab/ABC#11]
The file op132_no15_mov2.mscx is 13.5 megabytes, which is too long -- some kind of bug there.

**Comment by craigsapp** [comment]
This is because there are 53248 duplicated `<Jump>` elements in the file, so they are the result of some software recursion error most likely.  So no data corruption.

26624 at the end of the Violin 1 part, and 26624 at the end of the Cello part:

```xml
      <Measure number="245">
        <Jump>
          <track>12</track>
          <style>Repeat Text Right</style>
          <text>D.C. al Fine</text>
          <jumpTo>start</jumpTo>
          <playUntil>fine</playUntil>
          <continueAt></continueAt>
          </Jump>
        <Jump>
          <track>12</track>
          <style>Repeat Text Right</style>
          <text>D.C. al Fine</text>
          <jumpTo>start</jumpTo>
          <playUntil>fine</playUntil>
          <continueAt></continueAt>
          </Jump>
        <Jump>
          <track>12</track>
          <style>Repeat Text Right</style>
          <text>D.C. al Fine</text>
          <jumpTo>start</jumpTo>
          <playUntil>fine</playUntil>
          <continueAt></continueAt>
          </Jump>
[etc.]
```

After removing the duplicated lines, the file is 1.1 MB, compared to 13.2 MB originally.

Here is the file with the duplicate `<Jump>` messages removed (leaving 1 in the Violin 1 and 1 in the Cello part in case they are needed).  There were none in the Violin 2 and Viola parts:

[op132_no15_mov2.zip](https://github.com/DCMLab/ABC/files/5338483/op132_no15_mov2.zip)

(could also be sent as a Pull Request if you know how to deal with them).

The only other file to have `<Jump>` elements is op59_no8_mov3.mscx: only a single one in measure 142 in the Violin 1 part.

**Comment by johentsch** [comment]
Hi there, thank you for your reports. Actually, we have an update in the pipeline with renamed MuseScore 3 files which have been professionally corrected. Also, we are planning to review the annotations because our standard has gotten a couple of new features in between, but for now, you might be interested in using version 2 which should have fewer errors overall: https://github.com/DCMLab/ABC/tree/v2 Feel free to reopen the issue if it doesn't solve the issue.
