### ISSUE TITLE
Apparent issue in n13op130_01.tsv

### ISSUE THREAD

**Issue by malcolmsailor** [DCMLab/ABC#25]
In [measure 142 of n13op130_01.tsv](https://github.com/DCMLab/ABC/blob/v2/harmonies/n13op130_01.tsv#L445) the harmony is designated as "#vii+/vi". Here's the measure in question:

<img width="313" alt="Screen Shot 2022-08-03 at 2 13 12 PM" src="https://user-images.githubusercontent.com/28103673/182679467-b25e714a-c076-4fac-9eec-72516fe1314a.png">
 
The pitch-classes of this harmony are B-natural, E-flat, and G. The annotation seems wrong in at least two ways:
1. The key is B-flat, so vi would be G. Presumably, the secondary roman numeral is meant to be ii (C), not vi (G).
2. Upper case is ordinarily used for augmented chords. I did a grep on all the tsv files in harmonies and this seems to be the only case where a lower-case roman numeral is followed by '+'.

**Comment by johentsch** [comment]
Thank you, @malcolmsailor ! The local key changes to Eb in the previous measure 141 but this doesn't change in the TSV because it occurred in the alternative label only. I've created PR #27 to fix that.

The `/vi` part thus being correct, you are right about augmented chords always written in upper case. But additionally, augmented chords consist of two stacked major thirds, meaning that Eb should be considered the root of this chord. Therefore I've corrected the label to `III+6/vi`.

**Comment by malcolmsailor** [comment]
Thanks for the prompt fix!

> But additionally, augmented chords consist of two stacked major thirds, meaning that Eb should be considered the root of this chord. Therefore I've corrected the label to `III+6/vi`.

Yes, this is why I said "at least" two problems ;) I wasn't sure whether you were being enharmonically correct about augmented triads. But shouldn't it be III+6/4 (with B in the bass) rather than III+6 (which would be G in the bass)?

**Comment by johentsch** [comment]
Yes, thanks for paying at least as much attention as I should have! I cut through red tape and committed the fix of the fix to v2.
