### ISSUE TITLE
#viio should not be used for relative major keys

### ISSUE THREAD

**Issue by johentsch** [DCMLab/ABC#6]
In major keys, the diminished triad (and related 7th chords) on the leading tone is viio, not #viio. That is to say, #viio does not exist in the context of major keys and annotations such as #viio/V should be corrected to viio/V.

**Comment by fabianmoss** [comment]
Yes. The guidelines should state unequivocally, that the `root` part of a chord symbol refers to diatonic roots, i.e. major and natural minor steps. Theoretically, a `#viio7` in major is possible but extremely unlikely. It would be a `c#o7` in C major, which is almost certainly better expressed in relation to another chord or key -- I just want to point out that it is not necessarily a semantic error.

**Comment by MarkGotham** [comment]
Glad to see this issue is already on your radar.

This seems to be a consistent error, so it may be worth running a fix across the corpus. For a basic check / remedial fix / first parse:
- if the locally operational key is major (local key, relative root etc.);
- and you have #vii
- simply delete ‘#’ from the numeral and 'chord' (combined column 0).

I’m pretty confident that this would be an improvement in every case. At least, I can think of no musical case in which we would want #viio in major. IMO, in the extremely rare case that the chord appears, even ‘viio/#I’ would be a better expression of its apparent function.

I’ve implemented this for my own purposes (dataset only — not the mscz scores) and am happy to share the code if you like.

Thanks and all the best for version 2!

**Comment by MarkGotham** [comment]
Great!
